name: Mypy Check
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Mypy Check
        uses: jpetrucciani/mypy-check@master
        with:
          path: 'manyworlds/'
